### ISSUE TITLE
Can't find real URL for JDBCTEmplate query

### ISSUE THREAD

**Issue by AIRAT1** [AIRAT1/web-app#2]
Пытаюсь воспроизвести ДЗ и добавить реализацию JDBCTemplate, но не могу понять откуда взять URL для БД. В прошлом примере мы создавали БД сами и URL был понятен. Здесь отдебажив метод из видео нашёл и вставил URL как в примере, но на данном методе программа падает в SQLiteException -> [SQLITE_ERROR] SQL error or missing database (no such table: autos). Это ведь из за не верного URL? Как понять какой URL тут нужен? Спасибо!

public List<Auto> getAll() throws SQLException{
        return JDBCTemplate.executeQuery(
                "jdbc:sqlite::memory:",
                "SELECT id, name, description, image FROM autos;",
                rs -> new Auto(
                        rs.getString("id"),
                        rs.getString("name"),
                        rs.getString("description"),
                        rs.getString("image")
                ));
    }

**Comment by coursar** [comment]
Так же вытаскиваете через JNDI, только это лучше сделать один раз в сервисе (а не каждый раз в самом jdbctemplate)

**Comment by coursar** [comment]
Вы через JNDI должны вытащить `DataSource` и вместо URL'а в `JdbcTemplate` передавать уже `DataSource`.

А в `JdbcTemplate` уже в методах делаете:
```java
try (Connection conn = dataSource.getConnection()) { ... }
```
